name: Complex workflow
on:
  push:
jobs:
  ubuntu:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v3
      - name: Step two
        run: date
  windows:
    name: Second job
    runs-on: windows-latest
    steps:
      - name: Step one
        uses: actions/checkout@v3
      - name: Step two
        run: date
  mac-os:
    name: Third job
    runs-on: macos-latest
    steps:
      - name: Step one
        uses: actions/checkout@v3
      - name: Step two
        run: date
  depends:
    name: Fourth job
    runs-on: ubuntu-latest
    needs: [ubuntu, windows, mac-os]
    steps:
      - name: Step one
        uses: actions/checkout@v3
      - name: Step two
        run: date
  
